import Img_Porto_1 from '../assets/gamma_paint.jpg';
import Img_Porto_2 from '../assets/corporateaccountability.jpg';
import Img_Porto_3 from '../assets/ufoe.jpg';

const PortfolioData = [
    {
        slug: "gamma-paint",
        title: "Gamma Paint",
        subtitle: "Company Profile",
        description: "Gamma Paint is the official website of a Jakarta-based paint manufacturing company that specializes in producing high-quality special effects and texture paints. The platform serves as a corporate portfolio and catalog showcasing their eco-friendly coatings and professional architectural services.",
        shortDescription: "Gamma Paint is a Jakarta-based manufacturer specializing in premium, eco-friendly special effects and texture paints for residential and commercial projects.",
        image: Img_Porto_1,
        heroBgColor: '#333333',
        linkWork: "#",
        label: ["CodeIgniter", "PHP", "Tailwind CSS", "Figma", "GSAP"],
        imageOrder: 2,
        textOrder: 1,
        year: "2024",
        role: "Frontend Developer",
        duration: "2 months",
        client: "Gamma Paint",
        associatedWith: "PT. Go Online Solusi",
        liveUrl: "https://www.gammapaint.com/",
        tools: ["CodeIgniter", "PHP", "Tailwind CSS", "Figma", "GSAP"],
        challenge: ["The client wanted a modern, animated company profile website.", "Needed a design system that reflects the Gamma Paint brand.", "Required a user-friendly interface for showcasing products and services."],
        solution: "I designed a modern company profile website for Gamma Paint. The project features a comprehensive design system, advanced animations, and a user-friendly interface. The website includes detailed product and service showcases, an interactive timeline of the company's history, and a modern portfolio section for their projects.",
        results: [
            { metric: "3.8%", label: "Conversion Rate" },
            { metric: "+217%", label: "Increase vs. Previous" },
            { metric: "1.2s", label: "First Contentful Paint" },
            { metric: "98", label: "Lighthouse Score" },
        ],
        gallery: [Img_Porto_1, Img_Porto_2],
    },
    {
        slug: "corporate-accountability",
        title: "Corporate Accountability",
        subtitle: "Company Profile",
        description: "Corporate Accountability is the official website of a global non-profit organization dedicated to stopping transnational corporations from devastating democracy, trampling human rights, and destroying the planet. Founded in 1977, the organization runs aggressive grassroots campaigns to shift power away from corporate giants and back to local communities.",
        shortDescription: "Corporate Accountability is a non-profit organization that wages global grassroots campaigns to stop transnational corporations from abusing human rights, undermining democracy, and damaging the environment.",
        image: Img_Porto_2,
        linkWork: "#",
        heroBgColor: '#68CBC5',
        label: ["Bootstrap", "Photoshop"],
        imageOrder: 1,
        textOrder: 2,
        year: "2023",
        role: "Frontend Developer",
        duration: "4 months",
        client: "Corporate Accountability",
        associatedWith: "Freelance",
        liveUrl: "https://corporateaccountability.org/",
        tools: ["Bootstrap", "Photoshop"],
        challenge: ["Balancing high-intensity activism imagery with dense financial reporting layouts cleanly.", "Maintaining strict contrast standards and readable structures across highly packed multi-column navigation menus"],
        solution: "Conducted a full UX audit and card-sorting sessions with 8 power users to understand their mental models. Consolidated the 12 screens into a unified dashboard with a persistent sidebar and a modular widget system. Built a shared component library with Recharts for all data visualizations and implemented real-time updates via Supabase subscriptions.",
        results: [
            { metric: "-40%", label: "Time on Task" },
            { metric: "4.7/5", label: "User Satisfaction" },
            { metric: "30+", label: "Reusable Components" },
            { metric: "0ms", label: "Data Stale Time" },
        ],
        gallery: [Img_Porto_2, Img_Porto_3],
    },
    {
        slug: "ufoelektronika",
        title: "Ufoelektronika",
        subtitle: "E-Commerce",
        description: "UFO Elektronika is a major Indonesian retail chain providing a wide range of home electronics, gadgets, and furniture through its physical branches and e-commerce platform. The site features various product categories, including home entertainment and appliances, alongside services like home delivery, secure payments, and promotional discounts.",
        shortDescription: "UFO Elektronika is a major Indonesian retail chain providing a wide range of home electronics, gadgets, and furniture through its physical branches and e-commerce platform.",
        image: Img_Porto_3,
        heroBgColor: '#C4FFDA',
        linkWork: "#",
        label: ["Opencart", "PHP", "Bootstrap", "Figma", "GSAP"],
        imageOrder: 2,
        textOrder: 1,
        year: "2023",
        role: "Frontend Developer",
        duration: "5 months",
        client: "Ufoelektronika",
        associatedWith: "PT. Go Online Solusi",
        liveUrl: "https://www.ufoelektronika.com/",
        tools: ["Opencart", "PHP", "Bootstrap", "Figma", "GSAP"],
        challenge: ["Designing complex, multi-tiered filter systems that remain easy to use on mobile screens when sorting through thousands of technical specs (e.g., filtering laptops by RAM, processor, and price simultaneously).", "Creating a clear user flow for buying online and picking up in-store without confusing customers about stock locations or pickup deadlines.", " Keeping a checkout screen simple and clean while offering massive variation in payment options (Virtual Accounts, e-wallets, credit card installments).", "Adapting dense electronic specification sheets into responsive, readable product pages that fit perfectly on narrow mobile devices."],
        solution: "Designed a motion-first design language where every interaction had a physical, tactile feel: card flip animations for account switching, spring-based gesture controls for swipe actions, and a custom haptic feedback system. All flows were accessibility-audited and tested with screen readers. The PWA was installable on Android and iOS with offline capability for balance checks.",
        results: [
            { metric: "4.9★", label: "App Store Rating" },
            { metric: "AA", label: "WCAG Compliance" },
            { metric: "12K+", label: "Users in Month 1" },
            { metric: "78%", label: "D30 Retention" },
        ],
        gallery: [Img_Porto_3, Img_Porto_1],
    },
];

export { PortfolioData };

