import Img_Porto_1 from '../assets/gamma_paint.webp';
import Img_Porto_2 from '../assets/corporateaccountability.webp';
import Img_Porto_3 from '../assets/ufoe.webp';
import Img_Porto_4 from '../assets/orix.webp';
import Img_Porto_5 from '../assets/kaltim_methanol.webp';
import Img_Porto_6 from '../assets/indika_energy.webp';
import Img_Associated_1 from '../assets/gositus_logo.webp'
import Img_Associated_2 from '../assets/stucel_logo.webp'

const PortfolioData = [
    {
        slug: "gamma-paint",
        title: "Gamma Paint",
        subtitle: "Company Profile",
        description: "Gamma Paint is the official website of a Jakarta-based paint manufacturing company that specializes in producing high-quality special effects and texture paints. The platform serves as a corporate portfolio and catalog showcasing their eco-friendly coatings and professional architectural services.",
        shortDescription: "Gamma Paint is a Jakarta-based manufacturer specializing in premium, eco-friendly special effects and texture paints for residential and commercial projects.",
        image: Img_Porto_1,
        heroBgColor: 'oklch(0.98 0.01 90)',
        linkWork: "#",
        label: ["CodeIgniter", "PHP", "Tailwind CSS", "Figma", "GSAP"],
        imageOrder: 2,
        textOrder: 1,
        year: "2024",
        role: "Frontend Developer",
        duration: "2 months",
        client: "Gamma Paint",
        associatedImg: Img_Associated_1,
        associatedName: "Associated with PT. Go Online Solusi",
        liveUrl: "https://www.gammapaint.com/",
        tools: ["CodeIgniter", "PHP", "Tailwind CSS", "Figma", "GSAP"],
        challenge: ["The client wanted a modern, animated company profile website.", "Needed a design system that reflects the Gamma Paint brand.", "Required a user-friendly interface for showcasing products and services."],
        solution: "I designed a modern company profile website for Gamma Paint. The project features a comprehensive design system, advanced animations, and a user-friendly interface. The website includes detailed product and service showcases, an interactive timeline of the company's history, and a modern portfolio section for their projects.",
        results: [
            { metric: "3.8%", label: "Conversion Rate" },
            { metric: "+217%", label: "Increase vs. Previous" },
            { metric: "1.2s", label: "First Contentful Paint" },
            { metric: "98", label: "Lighthouse Score" },
        ],
        gallery: [Img_Porto_1, Img_Porto_2],
    },
    {
        slug: "corporate-accountability",
        title: "Corporate Accountability",
        subtitle: "Company Profile",
        description: "Corporate Accountability is the official website of a global non-profit organization dedicated to stopping transnational corporations from devastating democracy, trampling human rights, and destroying the planet. Founded in 1977, the organization runs aggressive grassroots campaigns to shift power away from corporate giants and back to local communities.",
        shortDescription: "Corporate Accountability is a non-profit organization that wages global grassroots campaigns to stop transnational corporations from abusing human rights, undermining democracy, and damaging the environment.",
        image: Img_Porto_2,
        linkWork: "#",
        heroBgColor: 'oklch(0.98 0.01 90)',
        label: ["Bootstrap", "Photoshop"],
        imageOrder: 1,
        textOrder: 2,
        year: "2023",
        role: "Frontend Developer",
        duration: "4 months",
        client: "Corporate Accountability",
        associatedImg: null,
        associatedName: null,
        liveUrl: "https://corporateaccountability.org/",
        tools: ["Bootstrap", "Photoshop"],
        challenge: ["Balancing high-intensity activism imagery with dense financial reporting layouts cleanly.", "Maintaining strict contrast standards and readable structures across highly packed multi-column navigation menus"],
        solution: "Conducted a full UX audit and card-sorting sessions with 8 power users to understand their mental models. Consolidated the 12 screens into a unified dashboard with a persistent sidebar and a modular widget system. Built a shared component library with Recharts for all data visualizations and implemented real-time updates via Supabase subscriptions.",
        results: [
            { metric: "-40%", label: "Time on Task" },
            { metric: "4.7/5", label: "User Satisfaction" },
            { metric: "30+", label: "Reusable Components" },
            { metric: "0ms", label: "Data Stale Time" },
        ],
        gallery: [Img_Porto_2, Img_Porto_3],
    },
    {
        slug: "ufoelektronika",
        title: "Ufoelektronika",
        subtitle: "E-Commerce",
        description: "UFO Elektronika is a major Indonesian retail chain providing a wide range of home electronics, gadgets, and furniture through its physical branches and e-commerce platform. The site features various product categories, including home entertainment and appliances, alongside services like home delivery, secure payments, and promotional discounts.",
        shortDescription: "UFO Elektronika is a major Indonesian retail chain providing a wide range of home electronics, gadgets, and furniture through its physical branches and e-commerce platform.",
        image: Img_Porto_3,
        heroBgColor: 'oklch(0.98 0.01 90)',
        linkWork: "#",
        label: ["Opencart", "PHP", "Bootstrap", "Figma", "GSAP"],
        imageOrder: 2,
        textOrder: 1,
        year: "2023",
        role: "Frontend Developer",
        duration: "5 months",
        client: "Ufoelektronika",
        associatedImg: Img_Associated_1,
        associatedName: "Associated with PT. Go Online Solusi",
        liveUrl: "https://www.ufoelektronika.com/",
        tools: ["Opencart", "PHP", "Bootstrap", "Figma", "GSAP"],
        challenge: ["Designing complex, multi-tiered filter systems that remain easy to use on mobile screens when sorting through thousands of technical specs (e.g., filtering laptops by RAM, processor, and price simultaneously).", "Creating a clear user flow for buying online and picking up in-store without confusing customers about stock locations or pickup deadlines.", " Keeping a checkout screen simple and clean while offering massive variation in payment options (Virtual Accounts, e-wallets, credit card installments).", "Adapting dense electronic specification sheets into responsive, readable product pages that fit perfectly on narrow mobile devices."],
        solution: "Designed a motion-first design language where every interaction had a physical, tactile feel: card flip animations for account switching, spring-based gesture controls for swipe actions, and a custom haptic feedback system. All flows were accessibility-audited and tested with screen readers. The PWA was installable on Android and iOS with offline capability for balance checks.",
        results: [
            { metric: "4.9★", label: "App Store Rating" },
            { metric: "AA", label: "WCAG Compliance" },
            { metric: "12K+", label: "Users in Month 1" },
            { metric: "78%", label: "D30 Retention" },
        ],
        gallery: [Img_Porto_3, Img_Porto_1],
    },
    {
        slug: "orix",
        title: "Orix",
        subtitle: "Company Profile",
        description: "PT ORIX Indonesia Finance is a joint venture leasing company between ORIX Corporation Japan and the Bank Indonesia Employee Welfare Foundation. Established in 1986, the company has grown into one of the leading multi-finance institutions in Indonesia, providing comprehensive financial solutions to both corporate and individual customers.",
        shortDescription: "PT ORIX Indonesia Finance is a joint venture leasing company between ORIX Corporation Japan and the Bank Indonesia Employee Welfare Foundation.",
        image: Img_Porto_4,
        linkWork: "#",
        heroBgColor: 'oklch(0.98 0.01 90)',
        label: ["CodeIgniter", "PHP", "Tailwind CSS", "Figma", "GSAP"],
        imageOrder: 1,
        textOrder: 2,
        year: "2026",
        role: "Frontend Developer",
        duration: "4 months",
        client: "Orix",
        associatedImg: Img_Associated_1,
        associatedName: "Associated with PT. Go Online Solusi",
        liveUrl: "https://www.orix.co.id/",
        tools: ["CodeIgniter", "PHP", "Tailwind CSS", "Figma", "GSAP"],
        challenge: ["Ensuring the website maintained a professional and trustworthy corporate image while incorporating modern design trends.", "Developing a seamless and intuitive user experience for a diverse range of users, including potential clients and investors.", "Balancing the need for comprehensive information about the company's services and financial solutions with a clean and uncluttered interface.", "Optimizing the website for various devices and screen sizes to ensure accessibility for all users."],
        solution: "Conducted a full UX audit and card-sorting sessions with 8 power users to understand their mental models. Consolidated the 12 screens into a unified dashboard with a persistent sidebar and a modular widget system. Built a shared component library with Recharts for all data visualizations and implemented real-time updates via Supabase subscriptions.",
        results: [
            { metric: "-40%", label: "Time on Task" },
            { metric: "4.7/5", label: "User Satisfaction" },
            { metric: "30+", label: "Reusable Components" },
            { metric: "0ms", label: "Data Stale Time" },
        ],
        gallery: [Img_Porto_2, Img_Porto_3],
    },
    {
        slug: "kaltim-methanol",
        title: "Kaltim Methanol",
        subtitle: "Company Profile",
        description: "KMI was established in 1991 and began commercial operations in 1998. Since then, we have steadily expanded our capabilities and strengthened our foundations. Throughout this journey, KMI’s culture has been shaped by teamwork and a spirit of never giving up. We believe that progress is never the work of one person alone, but the result of people supporting one another with trust and respect. At KMI, our core values are Integrity, Loyalty, and Professionalism. These values guide our decisions, shape our behavior, and define the standards we uphold in every task, every day. Our plant is a valuable asset; however, even more important, our people are our most precious and invisible asset. We continue to evolve by bringing together the wisdom of each individual and advancing through creativity and ingenuity, always seeking New Way New Value. With this spirit, we are committed to passing our remarkable culture on to future generations. We will continue developing our people, strengthening our organization, and building a workplace where everyone can contribute and grow. Driven by our values and united as one team, we will keep contributing to the Nation and to communities—today and in the future.",
        shortDescription: "PT Kaltim Methanol Industri is a company in the basic chemical industry that produces methanol with a production capacity of 660,000 metric tons per year, using natural gas and CO₂ from Carbon Capture and Utilization (CCU) as feedstocks.",
        image: Img_Porto_5,
        linkWork: "#",
        heroBgColor: 'oklch(0.98 0.01 90)',
        label: ["CodeIgniter", "PHP", "Tailwind CSS", "Figma"],
        imageOrder: 1,
        textOrder: 2,
        year: "2026",
        role: "Frontend Developer",
        duration: "2 months",
        client: "Kaltim Methanol",
        associatedImg: Img_Associated_1,
        associatedName: "Associated with PT. Go Online Solusi",
        liveUrl: "https://www.kaltimmethanol.com/",
        tools: ["CodeIgniter", "PHP", "Tailwind CSS", "Figma"],
        challenge: ["Developing an intuitive interface for non-technical users to navigate and understand the company’s methanol production process.", "Creating a modern, dynamic visual experience while maintaining a formal, corporate tone.", "Balancing detailed company information with engaging visual storytelling.", "Ensuring mobile accessibility for stakeholders accessing the site on various devices."],
        solution: "Conducted a full UX audit and card-sorting sessions with 8 power users to understand their mental models. Consolidated the 12 screens into a unified dashboard with a persistent sidebar and a modular widget system. Built a shared component library with Recharts for all data visualizations and implemented real-time updates via Supabase subscriptions.",
        results: [
            { metric: "-40%", label: "Time on Task" },
            { metric: "4.7/5", label: "User Satisfaction" },
            { metric: "30+", label: "Reusable Components" },
            { metric: "0ms", label: "Data Stale Time" },
        ],
        gallery: [Img_Porto_2, Img_Porto_3],
    },
    {
        slug: "indika-energy",
        title: "Indika Energy",
        subtitle: "Company Profile",
        description: "The official website of PT Indika Energy Tbk showcases a leading diversified investment and integrated energy company in Indonesia, focusing on energy resources, services, and infrastructure. Its modern design combines professionalism with dynamic visual elements to convey the company’s vision and comprehensive business portfolio.",
        shortDescription: "The official website of PT Indika Energy Tbk showcases a leading diversified investment and integrated energy company in Indonesia, focusing on energy resources, services, and infrastructure. ",
        image: Img_Porto_6,
        linkWork: "#",
        heroBgColor: 'oklch(0.98 0.01 90)',
        label: ["Bootstrap", "Photoshop"],
        imageOrder: 1,
        textOrder: 2,
        year: "2024",
        role: "Frontend Developer",
        duration: "3 months",
        client: "Indika Energy",
        associatedImg: Img_Associated_2,
        associatedName: "Associated with Stucel",
        liveUrl: "https://www.indikaenergy.co.id/id/",
        tools: ["Bootstrap", "Photoshop"],
        challenge: ["Creating a modern, dynamic visual experience while maintaining a formal, corporate tone.", "Balancing detailed company information with engaging visual storytelling.", "Ensuring mobile accessibility for stakeholders accessing the site on various devices."],
        solution: "Conducted a full UX audit and card-sorting sessions with 8 power users to understand their mental models. Consolidated the 12 screens into a unified dashboard with a persistent sidebar and a modular widget system. Built a shared component library with Recharts for all data visualizations and implemented real-time updates via Supabase subscriptions.",
        results: [
            { metric: "-40%", label: "Time on Task" },
            { metric: "4.7/5", label: "User Satisfaction" },
            { metric: "30+", label: "Reusable Components" },
            { metric: "0ms", label: "Data Stale Time" },
        ],
        gallery: [Img_Porto_2, Img_Porto_3],
    },
];

export { PortfolioData };

